server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: iptv-site-service
  kafka:
    bootstrap-servers: kafka.lego-kafka.svc.cluster.local:9092
#    bootstrap-servers: 20.249.185.137:9092
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.workflow.common.event"
        spring.json.type.mapping: >
          workflow-step:com.workflow.common.event.WorkflowStepEvent,
          workflow-creation:com.workflow.common.event.WorkflowCreationEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mappings: >
          workflow-step:com.workflow.common.event.WorkflowStepEvent,
          workflow-creation:com.workflow.common.event.WorkflowCreationEvent
          
  datasource:
    url: jdbc:postgresql://postgres-iptv-site-postgresql.lego-db.svc.cluster.local:5432/dbname
    #url: ${POSTGRES_URL:jdbc:postgresql://4.230.157.136:5432/lego-db}
    username: ${POSTGRES_USER:lego-user}
    password: ${POSTGRES_PASSWORD:lego-pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        # 낙관적 락 설정
        jdbc.batch_versioned_data: true

kafka:
  topics:
    creation:
      request: ${KAFKA_TOPIC_CREATION_REQUEST:workflow.creation.request}
    step:
      request: ${KAFKA_TOPIC_STEP_REQUEST:workflow.internet.step.request}
      response: ${KAFKA_TOPIC_STEP_RESPONSE:workflow.internet.step.response}

spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true

logging:
  level:
    com.workflow: ${LOG_LEVEL:DEBUG}
