server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    activate:
      on-profile: dev
  application:
    name: workflow-acl-service

kafka:
  bootstrap-servers: 4.230.148.194:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  topics:
    internet:
      creation:
        request: ${KAFKA_TOPIC_INTERNET_CREATION_REQUEST:workflow.internet.creation.request}
    iptv:
      creation:
        request: ${KAFKA_TOPIC_IPTV_CREATION_REQUEST:workflow.iptv.creation.request}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    use-root-path: true

logging:
  level:
    com.workflow.acl: ${LOG_LEVEL:DEBUG}
